# Generated by Django 4.0.4 on 2022-06-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('semail', models.EmailField(max_length=254)),
                ('smobileno', models.IntegerField(verbose_name=10)),
                ('spassword', models.CharField(max_length=30)),
                ('sfaculty', models.CharField(default='foobar', max_length=30)),
                ('scourse', models.CharField(default='foobar', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', models.CharField(max_length=20)),
                ('temail', models.EmailField(max_length=254)),
                ('tpassword', models.CharField(max_length=20)),
                ('tmobileno', models.IntegerField(verbose_name=10)),
                ('tbranch', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.student')),
                ('sfaculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAPP.teaching')),
            ],
        ),
    ]
